### ISSUE TITLE
[Bug]: Broken link to Dask in the Overview of Ray notebook

### ISSUE THREAD

**Issue by znagler-bdai** [ray-project/ray-educational-materials#102]
### Notebook with bug

https://github.com/ray-project/ray-educational-materials/blob/main/Introductory_modules/Overview_of_Ray.ipynb

### What happened?

The link to "Dask on Ray" takes you to a 404 page:

https://docs.ray.io/en/latest/data/dask-on-ray.html

![image](https://github.com/ray-project/ray-educational-materials/assets/137222920/22752edc-e0ca-47af-aa13-fc653f747b0f)

It looks like it should be this page:

https://docs.ray.io/en/latest/ray-more-libs/dask-on-ray.html

### Environment info

N/A

### Issue Severity

Low: Minor problem.

**Comment by kamil-kaczmarek** [comment]
fixed in #105 .

thx!
