### ISSUE TITLE
[Suggestion]: Ray use cases section should split simple scaling vs advanced use cases

### ISSUE THREAD

**Issue by ericl** [ray-project/ray-educational-materials#16]
### Please share your suggestion here

Currently the list of use cases in https://github.com/ray-project/ray-educational-materials/blob/main/Introductory_modules/Overview_of_Ray.ipynb contains the following:
- Exoshuffle
- Building a custom feature engineering library
- Alpa
- RLlib / FIFA
- Multi-model serving
- RL training / Riot
- ML platform / Shopify
- ML platform / Spotify

This is skewed toward advanced use cases, which I don't think accurately reflects the entire target audience of Ray. I think it would be productive to break this down into two categories:
- **Scaling simple ML workloads**
  - Batch inference on CPUs and GPUs (Core / Data)
  - Parallel training of many small models / Distributed training of large models (Core / Train)
  - Managing parallel experiments and hyperparameter tuning (Tune)
  - Serving model pipelines or multiple models (Serve)
  - Reinforcement Learning (RLlib)
  - ML platform use cases (Shopify, Spotify)
- **Implementing advanced ML workloads**
  - Alpha
  - Exoshuffle
  - Custom feature eng library
  - RL training / Riot / FIFA

**Comment by kamil-kaczmarek** [comment]
thanks @ericl this is very helpful suggestion.

**Comment by kamil-kaczmarek** [comment]
@emmyscode it is related to the #15
