### ISSUE TITLE
[Bug]: Halt due to resources are not available 

### ISSUE THREAD

**Issue by luxunxiansheng** [ray-project/ray-educational-materials#75]
Example 3: How to use Ray distributed tasks for image transformation and computation

### What happened?

When I run the "run_distribued"， I had the following errors:

In my case I set the batch to 100  but even I set it to 35, the errors raised too. 

I am new to Ray and can not figure out what is going on .  What resouces are unavailable and why does the syestm halt?

![image](https://user-images.githubusercontent.com/26159816/224477147-4e534ab6-f243-46d4-bca3-b1f16ae244d1.png)

### Environment info

System: Centos 7
CPUs: 128
Ray: 2.3
python 3.9

### Issue Severity

None

**Comment by luxunxiansheng** [comment]
1.The mem seems O.K.  (>100G)
2. Yes, I have tried many times. 

The issue comes from the ray core I think.  If there are many tasks and the phyical CPUs  number is large, the errors will  definitely raise.   
 
Because I don't know who will be responsible to fix this bug, I have to post the issue at different places.  Sorry for that.

**Comment by kamil-kaczmarek** [comment]
Closed here: https://github.com/ray-project/ray/issues/33244
