### ISSUE TITLE
[Suggestion]: It's better to test the exmaples in the educational materials 

### ISSUE THREAD

**Issue by luxunxiansheng** [ray-project/ray-educational-materials#76]
### Please share your suggestion here

 predictions_dataset = predictor.predict(data=dataset, batch_size=1)

If I  run on a  GPU server,  this line will raise  a RayTaskError.  It seems 

the  returned segmentation_maps_postprocessed has to be put into CPU numpy and  the `num_gpus_per_worker=1'  has to be set.   It took me much time to   realize the example has that issue. For a newbie, even a minor issue may lead to confusion. 

Thanks

**Comment by kamil-kaczmarek** [comment]
Thanks for the comment!
