### ISSUE TITLE
[Suggestion]: No link to ray dashboard as instructed

### ISSUE THREAD

**Issue by arindamchoudhury** [ray-project/ray-educational-materials#87]
### Please share your suggestion here

hi,

I dont see any link to ray dashboard as instructed:

![Screenshot from 2023-06-11 12-46-51](https://github.com/ray-project/ray-educational-materials/assets/1412069/31644f4e-59f5-408f-8960-56dca7815899)

**Comment by kamil-kaczmarek** [comment]
@arindamchoudhury do you run it in Google Colab?

**Comment by arindamchoudhury** [comment]
no, in my laptop.
