### ISSUE TITLE
[Bug]: Ray_Core/ray_core_1_remote_functions.ipynb invalid import

### ISSUE THREAD

**Issue by mikeguyon98** [ray-project/ray-educational-materials#98]
### Notebook with bug

https://github.com/ray-project/ray-educational-materials/blob/main/Ray_Core/Ray_Core_1_Remote_Functions.ipynb

### What happened?

The first line of example 3 includes the following import: `import tasks_helper_utils as t_utils`. But, `tasks_helper_utils` is not a real library.

### Environment info

ray, version 2.7.0, Python 3.11.5, MacOS Monterey 12.2.1

### Issue Severity

Low: Minor problem.

**Comment by kamil-kaczmarek** [comment]
@mikeguyon98 

`tasks_helper_utils` is a [file](https://github.com/ray-project/ray-educational-materials/blob/main/Ray_Core/tasks_helper_utils.py) in the Ray Core directory.
